# Generated by Django 5.0.6 on 2024-06-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_restaurant_name_favorite_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
