# Generated by Django 5.0.6 on 2024-06-30 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_favorite_place_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
