# Generated by Django 5.0.6 on 2024-06-28 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='restaurant_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='phone_number',
            new_name='number',
        ),
    ]
